// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowApresentacao.Tests.FormulariodeContato
{
    using TechTalk.SpecFlow;
    using Autofac;
    using Autofac.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Formulario de Contato")]
    public partial class FormularioDeContatoFeature
    {
        
        private OpenQA.Selenium.IWebDriver driver;
        
        private IContainer container;
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Formulario.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationSettingsReader());
            this.container = builder.Build();
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Formulario de Contato", "Eu como usuário, preciso contactar o prestador de serviço\nPara que seja necessári" +
                    "o um possível retorno\nPreciso preencher as informações corretamente.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
            try { System.Threading.Thread.Sleep(50); this.driver.Quit(); } catch (System.Exception) {}
            this.driver = null;
            ScenarioContext.Current.Remove("Driver");
            ScenarioContext.Current.Remove("Container");
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            if(this.driver != null)
                ScenarioContext.Current.Add("Driver", this.driver);
            if(this.container != null)
                ScenarioContext.Current.Add("Container", this.container);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        private void InitializeSelenium(string browser)
        {
            this.driver = this.container.ResolveNamed<OpenQA.Selenium.IWebDriver>(browser);
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Preenchimento do formulario corretamente")]
        [NUnit.Framework.CategoryAttribute("after")]
        [NUnit.Framework.TestCaseAttribute("Chrome", "Franklin", "franklinjob@hotmail.com", "(21)991475281", "Teste de Mensagem", null, Category="Chrome", TestName="PreenchimentoDoFormularioCorretamente on Chrome with: \"Franklin\" ,\"franklinjob@ho" +
            "tmail.com\" ,\"(21)991475281\" ,\"Teste de Mensagem\"")]
        public virtual void PreenchimentoDoFormularioCorretamente(string browser, string nome, string e_Mail, string telefone, string mensagem, string[] exampleTags)
        {
            InitializeSelenium(browser);
            string[] @__tags = new string[] {
                    "after",
                    "Browser:Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Preenchimento do formulario corretamente", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("que eu esteja no site jobmidia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 10
 testRunner.When("eu clicar no link contato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 11
 testRunner.And(string.Format("para entrar em contato e necessario informar todos os dados obrigatorios do formu" +
                        "lario: {0},{1},{2},{3}", nome, e_Mail, telefone, mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.When("eu clicar em Enviar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 13
 testRunner.Then("o site ira informar a mensagem \'Sua mensagem foi enviada com sucesso.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Preenchimento do formulario com email incorreto")]
        [NUnit.Framework.CategoryAttribute("after")]
        [NUnit.Framework.TestCaseAttribute("Chrome", "Franklin", "franklinjob", "(21)991475281", "Teste de Mensagem", null, Category="Chrome", TestName="PreenchimentoDoFormularioComEmailIncorreto on Chrome with: \"Franklin\" ,\"franklinj" +
            "ob\" ,\"(21)991475281\" ,\"Teste de Mensagem\"")]
        public virtual void PreenchimentoDoFormularioComEmailIncorreto(string browser, string nome, string e_Mail, string telefone, string mensagem, string[] exampleTags)
        {
            InitializeSelenium(browser);
            string[] @__tags = new string[] {
                    "after",
                    "Browser:Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Preenchimento do formulario com email incorreto", @__tags);
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("que eu esteja no site jobmidia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
 testRunner.When("eu clicar no link contato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
 testRunner.And(string.Format("para entrar em contato e necessario informar todos os dados obrigatorios corretam" +
                        "ente exceto email: {0},{1},{2},{3}", nome, e_Mail, telefone, mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.Then("o formulario irá alertar o preenchimento incorreto do email \'Formato de e-mail in" +
                    "válido\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Preenchimento do formulario com email incorreto e alerta incorreto")]
        [NUnit.Framework.CategoryAttribute("after")]
        [NUnit.Framework.TestCaseAttribute("Chrome", "Franklin", "franklinjob", "(21)991475281", "Teste de Mensagem", null, Category="Chrome", TestName="PreenchimentoDoFormularioComEmailIncorretoEAlertaIncorreto on Chrome with: \"Frank" +
            "lin\" ,\"franklinjob\" ,\"(21)991475281\" ,\"Teste de Mensagem\"")]
        public virtual void PreenchimentoDoFormularioComEmailIncorretoEAlertaIncorreto(string browser, string nome, string e_Mail, string telefone, string mensagem, string[] exampleTags)
        {
            InitializeSelenium(browser);
            string[] @__tags = new string[] {
                    "after",
                    "Browser:Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Preenchimento do formulario com email incorreto e alerta incorreto", @__tags);
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
 testRunner.Given("que eu esteja no site jobmidia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 35
 testRunner.When("eu clicar no link contato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 36
 testRunner.And(string.Format("para entrar em contato e necessario informar todos os dados obrigatorios corretam" +
                        "ente exceto email: {0},{1},{2},{3}", nome, e_Mail, telefone, mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 37
 testRunner.Then("o formulario irá alertar o preenchimento incorreto do email \'Formato de e-mail in" +
                    "válidos\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
